version: '3'
services:
  internet:
    build:
      context: ./Internet
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/internet-0.0.1-SNAPSHOT.war
    volumes: 
     - data:/home 
    ports: 
     - 8081:8080
  intranet:
    build:
      context: ./Intranet
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/intranet-0.0.1-SNAPSHOT.jar
        PORT: 8080
    volumes: 
     - data:/home 
    ports: 
     - 8082:8080
volumes: 
 data: