version: '3'
services:
  internet:
    image: hospitalitysystem_internet:latest
    deploy:
     replicas: 1
     resources:
       limits:
         cpus: "0.1"
         memory: 200M
     restart_policy:
       condition: on-failure
    volumes: 
     - data:/home 
    ports: 
     - 8081:8080
    networks:
      - webnet
  intranet:
    image: hospitalitysystem_intranet:latest
    deploy:
     replicas: 1
     resources:
       limits:
         cpus: "0.1"
         memory: 200M
     restart_policy:
       condition: on-failure
    volumes: 
     - data:/home 
    ports: 
     - 8082:8080
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: 
volumes: 
 data: